export const RECORD_EVENT_TITLE = 'RECORD_EVENT_TITLE';
export const RECEIVER_ADDRESS_SELECTED = 'RECEIVER_ADDRESS_SELECTED';
export const RECORD_EVENT_ADDRESS = 'RECORD_EVENT_ADDRESS';
export const RECORD_RESPONSIBLE = 'RECORD_RESPONSIBLE';
export const RECORD_FREQUENCY = 'RECORD_FREQUENCY';
export const RECORD_MULTIPLES_DAYS = 'RECORD_MULTIPLES_DAYS';
export const RECORD_SIMPLE_SELECT = 'RECORD_SIMPLE_SELECT';
export const RECORD_SWITCH_LABEL = 'RECORD_SWITCH_LABEL';
export const RECORD_DATE = 'RECORD_DATE';
export const SEND_TO_DB = 'SEND_TO_DB';
export const GET_EVENTS_FROM_DB = 'SEND_TO_DB';

export const DISPLAY_APP_BAR = 'DISPLAY_APP_BAR';
