
export const OPEN_DIALOG_EVENT = 'OPEN_DIALOG_EVENT';
export const RECORD_EVENT_TITLE = 'RECORD_EVENT_TITLE';
export const RECORD_EVENT_ADDRESS = 'RECORD_EVENT_ADDRESS';
export const RECORD_CONTACT = 'RECORD_CONTACT';
export const RECORD_CATEGORY = 'RECORD_CATEGORY';
export const RECORD_FREQUENCY = 'RECORD_FREQUENCY';
export const RECORD_MULTIPLES_DAYS = 'RECORD_MULTIPLES_DAYS';
export const RECORD_DATE = 'RECORD_DATE';
export const POST_AND_CLEAR_FIELDS = 'POST_AND_CLEAR_FIELDS';
export const GET_EVENT_LIST = 'GET_EVENT_LIST';
export const RECORD_SWITCH_LABEL = 'RECORD_SWITCH_LABEL';

export const DISPLAY_APP_BAR = 'DISPLAY_APP_BAR';
export const DISPLAY_ADD_RECEIVER_DIALOG = 'DISPLAY_ADD_RECEIVER_DIALOG';
