
export const OPEN_DIALOG_EVENT = 'OPEN_DIALOG_EVENT';
export const RECORD_EVENT_TITLE = 'RECORD_EVENT_TITLE';
export const RECORD_EVENT_ADDRESS = 'RECORD_EVENT_ADDRESS';
export const RECORD_CONTACT = 'RECORD_CONTACT';
export const RECORD_CATEGORY = 'RECORD_CATEGORY';
export const RECORD_FREQUENCY = 'RECORD_FREQUENCY';
export const RECORD_MULTIPLES_DAYS = 'RECORD_MULTIPLES_DAYS';
export const RECORD_DATE = 'RECORD_DATE';
export const POST_AND_CLEAR_FIELDS = 'POST_AND_CLEAR_FIELDS';
export const GET_EVENT_LIST = 'GET_EVENT_LIST';
export const RECORD_SWITCH_LABEL = 'RECORD_SWITCH_LABEL';
export const GET_CONTACT_LIST = 'GET_CONTACT_LIST';
export const CHECK_DAYS = 'CHECK_DAYS';

export const DISPLAY_DIALOG_RECEIVER = 'DISPLAY_DIALOG_RECEIVER';
export const DISPLAY_DIALOG_DELETE_RECEIVER = 'DISPLAY_DIALOG_DELETE_RECEIVER';

export const GET_RECEIVERS = 'GET_RECEIVERS';
export const GET_SELECTED_RECEIVER = 'GET_SELECTED_RECEIVER';
export const GET_CONTACTS = 'GET_CONTACTS';
export const LOG_OUT = 'LOG_OUT';
